#
# Cookbook Name:: horizon
# Attributes:: default
#
# Copyright 2012, AT&T, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Set to some text value if you want templated config files
# to contain a custom banner at the top of the written file
default["horizon"]["custom_template_banner"] = "
# This file autogenerated by Chef
# Do not edit, changes will be overwritten
"

# valid options: package, or git
default["horizon"]["install_method"] = "package"
default["horizon"]["release"] = node["openstack"]["release"]

# if install_method is git, the following attributes are used.
default["horizon"]["git_repo"] = "https://github.com/openstack/horizon.git"
default["horizon"]["git_revision"] = "master"
default["horizon"]["git_dest_dir"] = "/opt/stack"



default["horizon"]["debug"] = false

# This user's password is stored in an encrypted databag
# and accessed with openstack-common cookbook library's
# db_password routine.
default["horizon"]["db"]["username"] = "dash"

# The Keystone role used by default for users logging into the dashboard
default["horizon"]["keystone_default_role"] = "Member"

# This is the name of the Chef role that will install the Keystone Service API
default["horizon"]["keystone_service_chef_role"] = "keystone"

default["horizon"]["use_ssl"] = true
default["horizon"]["ssl"]["cert"] = "horizon.pem"
default["horizon"]["ssl"]["key"] = "horizon.key"

default["horizon"]["swift"]["enabled"] = "False"

default["horizon"]["theme"] = "default"

case node["platform"]
when "fedora", "centos", "redhat", "amazon", "scientific"
  default["horizon"]["ssl"]["dir"] = "/etc/pki/tls"
  default["horizon"]["local_settings_path"] = "/etc/openstack-dashboard/local_settings"
  # TODO(shep) - Fedora does not generate self signed certs by default
  default["horizon"]["platform"] = {
    "horizon_packages" => ["openstack-dashboard", "MySQL-python"],
    "package_overrides" => ""
  }
when "ubuntu", "debian"
  default["horizon"]["ssl"]["dir"] = "/etc/ssl"
  default["horizon"]["local_settings_path"] = "/etc/openstack-dashboard/local_settings.py"
  default["horizon"]["platform"] = {
    "horizon_packages" => ["lessc","openstack-dashboard", "python-mysqldb"],
    "package_overrides" => "-o Dpkg::Options::='--force-confold' -o Dpkg::Options::='--force-confdef'"
  }
  # dependencies when installed from source (git)
  default["horizon"]["source_platform"] = {
    "horizon_packages" => ["python-pip", "python-dev", "build-essential", "lessc", "python-mysqldb"],
    "package_overrides" => "-o Dpkg::Options::='--force-confold' -o Dpkg::Options::='--force-confdef'"
  }
end

default["horizon"]["dash_root_path"] = "/usr/share/openstack-dashboard"
if node["horizon"]["install_method"] == "git" then
  default["horizon"]["local_settings_path"] = "#{node["horizon"]["git_dest_dir"]}/horizon/openstack_dashboard/local/local_settings.py"
default["horizon"]["dash_root_path"] = "/#{node["horizon"]["git_dest_dir"]}/horizon"
end

default["horizon"]["dash_path"] = node["horizon"]["dash_root_path"] + "/openstack_dashboard"

default["horizon"]["stylesheet_path"] = node["horizon"]["dash_path"] + "/templates/_stylesheets.html"
default["horizon"]["wsgi_path"] = node["horizon"]["dash_path"] + "/wsgi/django.wsgi"
#default["horizon"]["session_backend"] = "memcached"
default["horizon"]["session_backend"] = "file"

default["horizon"]["ssl_offload"] = "false"


